apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mysql-template
  annotations:
    description: "MySQL server for development purposes"
    tags: "database,sql"
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${SERVICE_NAME}
    labels:
      app: ${SERVICE_NAME}
  type: Opaque
  stringData:
    database-name: ${MYSQL_DATABASE}
    database-password: ${MYSQL_PASSWORD}
    database-root-password: ${MYSQL_ROOT_PASSWORD}
    database-user: ${MYSQL_USER}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${SERVICE_NAME}
    labels:
      app: ${SERVICE_NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${SERVICE_NAME}
    labels:
      app: ${SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${SERVICE_NAME}
    template:
      metadata:
        labels:
          app: ${SERVICE_NAME}
      spec:
        containers:
        - image: registry.redhat.io/rhel8/mysql-80:${IMAGE_TAG}
          name: mysql
          env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: ${SERVICE_NAME}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: ${SERVICE_NAME}
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-root-password
                name: ${SERVICE_NAME}
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: ${SERVICE_NAME}
          ports:
          - containerPort: 3306
            name: mysql
          volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: db-volume
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$MYSQL_PASSWORD" mysqladmin -u $MYSQL_USER ping
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$MYSQL_PASSWORD" mysqladmin -u $MYSQL_USER ping
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: ${VOLUME_CAPACITY}
        volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: ${SERVICE_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    ports:
    - port: 3306
    selector:
      app: ${SERVICE_NAME}
parameters:
- name: MEMORY_LIMIT
  value: 512Mi
- name: SERVICE_NAME
  value: mysql
- name: MYSQL_USER
  value: user
- name: MYSQL_PASSWORD
  value: password
- name: MYSQL_ROOT_PASSWORD
  value: secret
- name: MYSQL_DATABASE
  value: sampledb
- name: VOLUME_CAPACITY
  value: 1Gi
- name: IMAGE_TAG
  value: "1"
