apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.serviceName }}-init-db
  labels:
    app: {{ .Values.serviceName }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 360
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
        role: client
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-db
        image: registry.redhat.io/rhel8/mysql-80:{{ .Values.imageTag }}
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: {{ .Values.serviceName }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: {{ .Values.serviceName }}
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: {{ .Values.serviceName }}
        command:
        - bash
        - -c
        - |
          echo "Waiting for database server"
          counter=9
          while [ $counter -gt 0 ]; do
            echo "$counter... "
            sleep 10
            MYSQL_PWD="$MYSQL_PASSWORD" mysqladmin -h{{ .Values.serviceName }} -u$MYSQL_USER ping && break
            let counter--
          done
          if [ $counter -eq 0 ]; then
            echo "Database server startup took too long :-(" 1>&2
            exit 1
          fi
      containers:
      - image: registry.redhat.io/rhel8/mysql-80:{{ .Values.imageTag }}
        name: init-db
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: {{ .Values.serviceName }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: {{ .Values.serviceName }}
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: {{ .Values.serviceName }}
        command:
        - bash
        - -c
        - |
          echo "Creating and populating the quotes table"
          # Source: https://www.freshworks.com/freshservice/general/top-it-quotes-blog/
          MYSQL_PWD="$MYSQL_PASSWORD" mysql -v -h{{ .Values.serviceName }} -u$MYSQL_USER $MYSQL_DATABASE <<SQL
          create table if not exists famousquotes (id integer primary key, quote varchar(200));
          truncate table famousquotes;
          insert into famousquotes values (1, 'The only constant in the technology industry is change.');
          insert into famousquotes values (2, 'The 4 Ps for Change and Release: Planning Prevents Poor Performance.');
          insert into famousquotes values (3, 'Any sufficiently advanced bug is indistinguishable from a feature.');
          insert into famousquotes values (4, 'IT is ever-changing and there is the need to evolve in order to stay relevant.');
          insert into famousquotes values (5, 'A Release is like a boat. 80% of the holes plugged is not good enough.');
          select * from famousquotes;
          SQL
